# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
coverage:
  status:
    patch:
      default:
        target: 80
    project:
      default: false
      auth:
        paths:
          - packages/auth
        threshold: 0.5
      gateway:
        paths:
          - packages/gateway
        threshold: 0.5
      login:
        paths:
          - packages/login
        threshold: 0.5
      notification:
        paths:
          - packages/notification
        threshold: 0.5
      client:
        paths:
          - packages/client
        threshold: 0.5
      user-mgnt:
        paths:
          - packages/user-mgnt
        threshold: 0.5
      commons:
        paths:
          - packages/commons
        threshold: 0.5
      workflow:
        paths:
          - packages/workflow
        threshold: 0.5
      search:
        paths:
          - packages/search
        threshold: 0.5
      metrics:
        paths:
          - packages/metrics
        threshold: 0.5
      config:
        paths:
          - packages/config
        threshold: 0.5
      documents:
        paths:
          - packages/documents
        threshold: 0.5

ignore:
  - 'packages/client/src/extract-translations.ts'
  - 'packages/client/src/index.tsx'
  - 'packages/client/src/registerServiceWorker.ts'
  - 'packages/client/src/src-sw.js'
  - 'packages/client/src/src-sw.ts'
  - 'packages/client/src/tests/graphql-schema-mock.ts'
  - 'packages/workflow/src/index.ts'
  - 'packages/gateway/src/index.ts'
  - 'packages/gateway/src/routes.ts'
  - 'packages/login/src/extract-translations.ts'
