coverage:
  status:
    patch:
      default:
        target: 80
    project:
      default: false
      auth:
        paths:
          - packages/auth
        threshold: 0.5
      gateway:
        paths:
          - packages/gateway
        threshold: 0.5
      login:
        paths:
          - packages/login
        threshold: 0.5
      notification:
        paths:
          - packages/notification
        threshold: 0.5
      register:
        paths:
          - packages/register
        threshold: 0.5
      performance:
        paths:
          - packages/performance
        threshold: 0.5
      user-mgnt:
        paths:
          - packages/user-mgnt
        threshold: 0.5
      validation:
        paths:
          - packages/validation
        threshold: 0.5
      workflow:
        paths:
          - packages/workflow
        threshold: 0.5
ignore:
  - 'packages/register/src/extract-translations.ts'
  - 'packages/register/src/index.tsx'
  - 'packages/register/src/registerServiceWorker.ts'
  - 'packages/register/src/src-sw.js'
  - 'packages/register/src/tests/graphql-schema-mock.ts'
