# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
before_install:
  # Workaround for a travis-ci failure issue. Need to remove it once they fix it.
  # See https://github.com/travis-ci/travis-ci/issues/8920
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - openssl aes-256-cbc -K $encrypted_6a4906510c0e_key -iv $encrypted_6a4906510c0e_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - sudo apt-get -y install apache2-utils
language: node_js
dist: bionic
node_js:
  - 'lts/*'
env:
  - CI=true

jobs:
  include:
    - stage: tests (unit and integration)
      script: yarn test && yarn lint
      after_success:
        - npm install codecov -g
        - codecov
      before_install: npm install -g yarn
    - if: type = pull_request
      before_install: npm install -g yarn && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      addons:
        apt:
          packages:
            - libgconf-2-4
      script:
        - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - ./infrastructure/build-and-test-e2e.sh
        - kill %1
      env:
        - OTHER_LERNA_FLAGS=""
        - CYPRESS_LOGIN_URL=http://localhost:3020/
        - CYPRESS_CLIENT_URL=http://localhost:3000/
        - CYPRESS_AUTH_URL=http://localhost:4040/
      services:
        - docker

    - stage: build and push docker images
      if: branch = master AND type = push
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn compose:push
      sudo: required
      services:
        - docker

    - stage: deploy to staging
      if: branch = master AND type = push
      install: skip
      script:
        - git clone https://github.com/opencrvs/opencrvs-zambia.git
        - bash deploy.sh --clear-data=no --restore-metadata=no --update-metadata=no development opencrvs-staging.jembi.org latest opencrvs-zambia
      addons:
        ssh_known_hosts: opencrvs-staging.jembi.org

    - stage: integration tests on staging
      if: branch = master AND type = push
      before_install: npm install -g yarn && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      addons:
        apt:
          packages:
            - libgconf-2-4
      script:
        - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - ./infrastructure/build-and-test-e2e-on-staging.sh
        - kill %1
      env:
        - CYPRESS_LOGIN_URL=https://login.opencrvs-staging.jembi.org/
        - CYPRESS_CLIENT_URL=https://register.opencrvs-staging.jembi.org/
        - CYPRESS_AUTH_URL=https://auth.opencrvs-staging.jembi.org/

notifications:
  slack:
    secure: DhI2stRdMYu43Nw1ZkYj8elOUc5gLmEKMponUp4seLYATmG8/MKL525yKnrQlvd88W1J1FX4SFSu0t/pl5n0iFOTNCUlw5WWu1hPotR02xrb85S9oDRGvIsOJYjPC/bh2nru1BJf3lgCfQCNRUQkrv2wWlrScuj0oF16ibbo5mLMX8iY/a3KDvWyhW7/mvK4KNHdxfNzocMHvZqassRDfIvJUM1SVNIGH7lavnhEzmUTahgQ9F0aydGUKzrx5V/KiI3yB+zzKYDtZj7D8DkSPfbyJ4OWflds+RzmQUn9ytqGTu+A8Gx53s4uEsdamTAKUHlJn1Lecdei6YWUgcd/WRGPB3EqJHAW7nkeWrqBjpn2v7muGz1K21vk140+96Gvwcin5sQ6u+e/axf/PYYXlKtOzAqkOnzTH+YjSM7Zv4yM1Qbl0RlaFoElSno+8BXhps76I+NGkIVllYvsEGbeIPUqbXApPIZgfvlj1Qxuvmz8xENLNOX0/U1ztZLaOa//orXAh8UMA2MqXIUkPbCk7PoQD5PQ8tnx5oQM/cZ3xTECdtjWDkVZjbU2puSANMj9Vxe747NzjoHabsXqHMuUvatS39s7k6jlW//G7kiPHzqGiSFQEPHZhRu7ekdG2r7otaqYuZNNBGvuDQJJVopro6gtT+Mqzv8jPTJ3IlG3zp0=
    on_success: never
    on_failure: always
    on_pull_requests: false
