language: node_js
node_js:
  - 'lts/*'
jobs:
  include:
    - stage: tests (unit and integration)
      after_success:
        - npm install codecov -g
        - codecov
    - before_install: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      addons:
        apt:
          packages:
            - libgconf-2-4
      script:
        - yarn global add wait-on
        - yarn dev:secrets:gen
        - docker swarm init
        - sudo mkdir -p data/elasticsearch
        - sudo chown -R 1000:1000 data/elasticsearch
        - yarn compose:all &
        - wait-on tcp:4040 tcp:3030 tcp:2020 tcp:7070 tcp:5050 tcp:9090 tcp:3040 tcp:1050 http://localhost:3000 http://localhost:3001 http://localhost:3020 tcp:27017 tcp:6379 tcp:9200 tcp:8086 tcp:3447 tcp:5001
        - yarn db:backup:restore
        - cd packages/resources && yarn save:testData && cd ../..
        - cd packages/e2e && yarn start --record false
      env:
        - OTHER_LERNA_FLAGS="--ignore @opencrvs/performance"
        - CYPRESS_LOGIN_URL=http://localhost:3020/
        - CYPRESS_REGISTER_URL=http://localhost:3000/
        - CYPRESS_PERFORMANCE_URL=http://localhost:3002/
        - CYPRESS_AUTH_URL=http://localhost:4040/
      services:
        - docker

    - stage: build and push docker images
      if: branch = master AND type = push
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn compose:push
      sudo: required
      services:
        - docker

    - stage: deploy to staging
      if: branch = master AND type = push
      install: skip
      script: yarn deploy:staging
      addons:
        ssh_known_hosts: opencrvs-staging.jembi.org

    - stage: integration tests on staging
      if: branch = master AND type = push
      install: skip
      addons:
        apt:
          packages:
            - libgconf-2-4
      script: cd packages/e2e && yarn && yarn start --record false
      env:
        - CYPRESS_LOGIN_URL=https://login.opencrvs-staging.jembi.org/
        - CYPRESS_REGISTER_URL=https://register.opencrvs-staging.jembi.org/
        - CYPRESS_PERFORMANCE_URL=https://performance.opencrvs-staging.jembi.org/
        - CYPRESS_AUTH_URL=https://auth.opencrvs-staging.jembi.org/

notifications:
  slack:
    secure: DhI2stRdMYu43Nw1ZkYj8elOUc5gLmEKMponUp4seLYATmG8/MKL525yKnrQlvd88W1J1FX4SFSu0t/pl5n0iFOTNCUlw5WWu1hPotR02xrb85S9oDRGvIsOJYjPC/bh2nru1BJf3lgCfQCNRUQkrv2wWlrScuj0oF16ibbo5mLMX8iY/a3KDvWyhW7/mvK4KNHdxfNzocMHvZqassRDfIvJUM1SVNIGH7lavnhEzmUTahgQ9F0aydGUKzrx5V/KiI3yB+zzKYDtZj7D8DkSPfbyJ4OWflds+RzmQUn9ytqGTu+A8Gx53s4uEsdamTAKUHlJn1Lecdei6YWUgcd/WRGPB3EqJHAW7nkeWrqBjpn2v7muGz1K21vk140+96Gvwcin5sQ6u+e/axf/PYYXlKtOzAqkOnzTH+YjSM7Zv4yM1Qbl0RlaFoElSno+8BXhps76I+NGkIVllYvsEGbeIPUqbXApPIZgfvlj1Qxuvmz8xENLNOX0/U1ztZLaOa//orXAh8UMA2MqXIUkPbCk7PoQD5PQ8tnx5oQM/cZ3xTECdtjWDkVZjbU2puSANMj9Vxe747NzjoHabsXqHMuUvatS39s7k6jlW//G7kiPHzqGiSFQEPHZhRu7ekdG2r7otaqYuZNNBGvuDQJJVopro6gtT+Mqzv8jPTJ3IlG3zp0=
    on_success: never
    on_failure: always
    on_pull_requests: false
