version: '3.3'

services:
  register:
    image: jembi/ocrvs-register:{{shortGitHash}}
    build:
      context: .
      dockerfile: ./Dockerfile-register
    restart: unless-stopped
    deploy:
      replicas: 2

  performance:
    image: jembi/ocrvs-performance:{{shortGitHash}}
    build:
      context: .
      dockerfile: ./Dockerfile-performance
    restart: unless-stopped
    deploy:
      replicas: 2

  login:
    image: jembi/ocrvs-login:{{shortGitHash}}
    build:
      context: .
      dockerfile: ./Dockerfile-login
    restart: unless-stopped
    deploy:
      replicas: 2

  gateway:
    image: jembi/ocrvs-gateway:{{shortGitHash}}
    build: packages/gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - WORKFLOW_SERVICE_URL=http://workflow:5050/
      - COUNTRY=bgd
    deploy:
      replicas: 2

  workflow:
    image: jembi/ocrvs-workflow:{{shortGitHash}}
    build: packages/workflow
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - COUNTRY=bgd
    deploy:
      replicas: 2

  auth:
    image: jembi/ocrvs-auth:{{shortGitHash}}
    build: packages/auth
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
    deploy:
      replicas: 2

  user-mgnt:
    image: jembi/ocrvs-user-mgnt:{{shortGitHash}}
    build: packages/user-mgnt
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo/user-mgnt
    deploy:
      replicas: 2

  notification:
    image: jembi/ocrvs-notification:{{shortGitHash}}
    build: packages/notification
    restart: unless-stopped
    environment:
      - LANGUAGE=bn
    deploy:
      replicas: 2
