version: '3.3'

services:
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    volumes:
      - '/data/mongo:/data/db'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - overlay_net

  redis:
    image: redis:5
    restart: unless-stopped
    networks:
      - overlay_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    restart: unless-stopped
    volumes:
      - '/data/elasticsearch:/usr/share/elasticsearch/data'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - overlay_net

  influxdb:
    image: influxdb:1.7
    restart: unless-stopped
    volumes:
      - '/data/influxdb:/var/lib/influxdb'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - overlay_net

  hearth:
    image: jembi/hearth:v1.0.0-beta.1
    environment:
      - mongodb__url=mongodb://mongo/hearth-dev
      - logger__level=error
      - authentication__type=disabled
      - idGenerator=uuidv4
      - server__fhirVersion=stu3
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

  openhim-core:
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo/openhim-dev
      - mongo_atnaUrl=mongodb://mongo/openhim-dev
      - logger_level=error
    ports:
      - '8080:8080'
      - '5000:5000'
      - '5001:5001'
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

  openhim-console:
    image: jembi/openhim-console:1.13
    ports:
      - '8888:80'
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

networks:
  overlay_net:
    driver: overlay
    attachable: true
