version: "3.3"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    logging:
      driver: none
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  hearth:
    image: jembi/hearth:latest
    environment:
      - mongodb__url=mongodb://mongo/hearth-dev
      - logger__level=error
      - authentication__type=disabled
      - idGenerator=uuidv4
    ports:
      - "3447:3447"
    restart: unless-stopped
    deploy:
      replicas: 2

  openhim-core:
    image: jembi/openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim-dev
      - mongo_atnaUrl=mongodb://mongo/openhim-dev
      - logger_level=error
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      replicas: 2

  openhim-console:
    image: jembi/openhim-console
    ports:
      - "8888:80"
    configs:
      - source: openhim-console-conf
        target: /usr/share/nginx/html/config/default.json
    restart: unless-stopped
    deploy:
      replicas: 2

configs:
  openhim-console-conf:
    file: ./infrastructure/openhim-console-config.json
