version: '3.3'

services:
  register:
    image: jembi/ocrvs-register:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile-register
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

  performance:
    image: jembi/ocrvs-performance:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile-performance
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

  login:
    image: jembi/ocrvs-login:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile-login
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - overlay_net

  gateway:
    image: jembi/ocrvs-gateway:${VERSION:-latest}
    build: packages/gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - COUNTRY=bgd
    deploy:
      replicas: 2
    networks:
      - overlay_net

  workflow:
    image: jembi/ocrvs-workflow:${VERSION:-latest}
    build: packages/workflow
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - HEARTH_URL=http://hearth:3447/fhir
      - OPENHIM_URL=http://openhim-core:5001
      - COUNTRY=bgd
    deploy:
      replicas: 2
    networks:
      - overlay_net

  deduplication:
    image: jembi/ocrvs-deduplication:${VERSION:-latest}
    build: packages/deduplication
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - ES_HOST=elasticsearch:9200
      - HEARTH_URL=http://hearth:3447/fhir
    deploy:
      replicas: 2
    networks:
      - overlay_net

  auth:
    image: jembi/ocrvs-auth:${VERSION:-latest}
    build: packages/auth
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
    deploy:
      replicas: 2
    networks:
      - overlay_net

  user-mgnt:
    image: jembi/ocrvs-user-mgnt:${VERSION:-latest}
    build: packages/user-mgnt
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo/user-mgnt
    deploy:
      replicas: 2
    networks:
      - overlay_net

  notification:
    image: jembi/ocrvs-notification:${VERSION:-latest}
    build: packages/notification
    restart: unless-stopped
    environment:
      - LANGUAGE=bn
    deploy:
      replicas: 2
    networks:
      - overlay_net

  resources:
    image: jembi/ocrvs-resources:${VERSION:-latest}
    build: packages/resources
    restart: unless-stopped
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
      - ADMINISTRATIVE_STRUCTURE_URL=http://174.136.37.245:8090/gen
    deploy:
      replicas: 2
    networks:
      - overlay_net
