name: 'alert'
type: 'frequency'
index: 'kibana-alert-history-default'
is_enabled: true
num_events: 1
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: 'iso'
use_strftime_index: false
# https://github.com/Yelp/elastalert/issues/1260
raw_count_keys: false
alert_subject: 'New Kibana {}: {} ⚠️'
alert_subject_args:
  - 'kibana.alert.context.metrics__alert__inventory__threshold.alertState'
  - 'rule.name'
alert_text: 'Reason: {}'
alert_text_args:
  - 'kibana.alert.context.metrics__alert__inventory__threshold.reason'
filter:
  - query:
      query_string:
        query: '@timestamp:*'
alert:
  - 'slack'
slack_webhook_url: 'https://hooks.slack.com/services/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'
slack_channel_override: '#kibana-alerts'
slack_emoji_override: ':kissing_cat:'
slack_msg_color: 'warning'
slack_parse_override: 'none'
slack_username_override: 'elastalert'
