apiVersion: v1
kind: Service
metadata:
  labels:
    app: search
  name: search
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: search
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: "opencrvs/ocrvs-search:{{ .Values.image.tag }}"
          env:
            - name: APPLICATION_CONFIG_URL
              value: {{ .Values.applicationConfigUrl }} # FIXME: harcoded/
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: ES_HOST
              value: {{ .Values.elasticHost }}
            - name: FHIR_URL
              value: {{ .Values.fhirUrl }} # FIXME: harcoded
            - name: HEARTH_MONGO_URL
              value: {{ .Values.mongoUrl }}/hearth-dev
            - name: NODE_ENV
              value: development
            - name: USER_MANAGEMENT_URL
              value: {{ .Values.userManagementUrl }} # FIXME: hardcoded
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: public-key
          name: public-key