# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

name: Check Missing Translation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  check-missing-translation:
    runs-on: ubuntu-latest

    steps:
    - name: Get the current branch name
      id: get_branch
      run: |
        echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        echo "We are currently on the branch $branch_name"

    - name: Create directory for core and countryconfig
      run: |
        mkdir -m 777 -p $HOME/core
        mkdir -m 777 -p $HOME/countryconfig
  
    - name: Clone countryconfig repository and check the branch if available in countryconfig or not
      id: set_branch
      run: |
        cd $HOME/countryconfig
        git clone https://github.com/opencrvs/opencrvs-countryconfig.git
        cd opencrvs-countryconfig

        if git show-ref --verify --quiet refs/heads/${steps.get_branch.outputs.branch_name}; then
          echo "working_branch=${steps.get_branch.outputs.branch_name}" >> $GITHUB_OUTPUT
        else
          echo "working_branch=develop" >> $GITHUB_OUTPUT
        fi
        echo "We will be working on the branch $working_branch"

    - name: Set branch in core and check if any missing translation exists
      run: |
        cd $HOME/core/
        

        # if [ "$branch_exists" = "true" ]; then
        #   git checkout $branch_name
        #   echo "Check out to branch $branch_name"
        # else
        #   git checkout develop
        #   echo "Check out to develop branch"
        # fi
        # sh packages/client/extract-translations.sh
    