# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

name: Check Missing Translation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  check-missing-translation:
    runs-on: ubuntu-latest

    steps:
    - name: Create directory for core
      run: mkdir -p /core
  
    - name: Checkout opencrvs-core repository
      uses: actions/checkout@v4
      with:
        path: /core

    - name: Get current branch name
      id: get_branch
      run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    
    - name: Clone countryconfig repository and check the branch if available in countryconfig or not
      run: |
        mkdir -p /countryconfig
        cd /countryconfig
        git clone https://github.com/opencrvs/opencrvs-countryconfig.git
        cd opencrvs-countryconfig
        if git show-ref --verify --quiet refs/heads/$branch_name; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branch_exists=false" >> $GITHUB_ENV
        fi

    - name: Set branch in core and check if any missing translation exists
      run: |
        cd /core/opencrvs-core/
        if [ "$branch_exists" = "true" ]; then
          git checkout $branch_name
          echo "Check out to branch $branch_name"
        else
          git checkout develop
          echo "Check out to develop branch"
        fi
        sh packages/client/extract-translations.sh
    